-- I'm New page content sections (When You Arrive, In The Service, After The Service, What to Expect)
INSERT INTO content_sections (section_key, title, content, extra_data, sort_order) VALUES
('im_new_arrive', 'I\'m New - When You Arrive', '<p>This is LightHouse, You are welcome! Upon arrival, you''ll find plenty of parking spaces, and our friendly greeters will be there to guide you every step of the way. Whether it''s your first visit or your hundredth, we want you to feel completely at ease.</p><p>If you''re visiting with children, our team will help you check them into our secure, age-appropriate classes designed to engage and inspire young hearts. Unsure where to go? Just ask anyone wearing a "Welcome Team" badge—they''re here to assist you!</p>', NULL, 19),
('im_new_arrive_summary', 'I\'m New - When You Arrive (card)', 'Upon arrival, you''ll find plenty of parking and our friendly greeters will guide you every step of the way. Our team will help with children''s check-in—just ask anyone wearing a Welcome Team badge.', NULL, 19),
('im_new_service', 'I\'m New - In The Service', '<p>Our service experience is uplifting, engaging, and designed to help you connect with God. Expect 2 to 3 hours of heartfelt worship with dynamic music and a mix of contemporary and multicultural songs reflecting our global community.</p><p>You''ll also hear an inspiring, gospel-centered message that''s relevant to your everyday life. Whether you''re new to faith or have been walking with Jesus for years, you''ll leave refreshed and equipped for the week ahead.</p><p>Feel free to participate at your comfort level—sing, clap, reflect, or simply soak it all in. We''re here to create a space for everyone to encounter God in their unique way.</p>', NULL, 20),
('im_new_service_summary', 'I\'m New - In The Service (card)', 'Experience 2–3 hours of heartfelt worship and an inspiring, gospel-centered message. Participate at your comfort level—sing, clap, reflect, or simply soak it all in.', NULL, 20),
('im_new_after', 'I\'m New - After The Service', '<p>After the service, we''d love for you to hang around and meet our church family! Our Connection Team is available to answer any questions and help you take your next steps, whether that''s learning more about the church, joining a small group, or simply finding a place to belong.</p><p>Stop by the Welcome Station located near the entrance to receive a special gift as our way of saying thank you for visiting. If you''re curious about faith, exploring your next steps, or just want to meet new friends, we''re excited to journey with you at The LightHouse!</p>', NULL, 21),
('im_new_after_summary', 'I\'m New - After The Service (card)', 'Hang around and meet our church family! Our Connection Team will help you take your next steps. Stop by the Welcome Station for a special gift.', NULL, 21),
('im_new_what_to_expect', 'I\'m New - What to Expect', '<ul><li>Engaging worship experiences that blend contemporary music with heartfelt moments.</li><li>Biblically rooted messages that inspire practical application in everyday life.</li><li>Fun and safe programs for kids of all ages.</li></ul>', NULL, 22)
ON DUPLICATE KEY UPDATE content = VALUES(content), sort_order = VALUES(sort_order);
